import { ConnectorConfig } from "./contants";



export function _mockApiResponse(_request: GoogleAppsScript.Data_Studio.Request<ConnectorConfig>) {
    return [
        {
            "sales_approved": "0",
            "leads_approved": "0",
            "currency": "UAH",
            "ctr": 107300.0,
            "views": 1,
            "payment_sum_declined": 0.0,
            "payment_sum_open": 1799.94,
            "payment_sum_approved": 0.0,
            "leads_declined": "0",
            "leads_open": "6",
            "sales_declined": "0",
            "ecpm": 1799940.0,
            "sales_open": "0",
            "date": "2020-10-21",
            "cr": 0.56,
            "ecpc": 1.68,
            "clicks": 1073,
        },
        {
            "sales_approved": "0",
            "leads_approved": "0",
            "currency": "UAH",
            "ctr": 12675.0,
            "views": 8,
            "payment_sum_declined": 0.0,
            "payment_sum_open": 3359.69,
            "payment_sum_approved": 0.0,
            "leads_declined": "0",
            "leads_open": "11",
            "sales_declined": "0",
            "ecpm": 419961.25,
            "sales_open": "1",
            "date": "2020-10-20",
            "cr": 1.18,
            "ecpc": 3.32,
            "clicks": 1014,
        },
        {
            "sales_approved": "0",
            "leads_approved": "0",
            "currency": "UAH",
            "ctr": 3116.67,
            "views": 36,
            "payment_sum_declined": 0.0,
            "payment_sum_open": 4199.86,
            "payment_sum_approved": 0.0,
            "leads_declined": "0",
            "leads_open": "14",
            "sales_declined": "0",
            "ecpm": 116662.78,
            "sales_open": "0",
            "date": "2020-10-19",
            "cr": 1.25,
            "ecpc": 3.75,
            "clicks": 1122,
        },
        {
            "sales_approved": "0",
            "leads_approved": "0",
            "currency": "UAH",
            "ctr": 13037.5,
            "views": 8,
            "payment_sum_declined": 0.0,
            "payment_sum_open": 3302.42,
            "payment_sum_approved": 0.0,
            "leads_declined": "0",
            "leads_open": "11",
            "sales_declined": "0",
            "ecpm": 412802.5,
            "sales_open": "1",
            "date": "2020-10-18",
            "cr": 1.15,
            "ecpc": 3.17,
            "clicks": 1043,
        },
        {
            "sales_approved": "0",
            "leads_approved": "0",
            "currency": "UAH",
            "ctr": 57150.0,
            "views": 2,
            "payment_sum_declined": 0.0,
            "payment_sum_open": 7499.75,
            "payment_sum_approved": 0.0,
            "leads_declined": "0",
            "leads_open": "25",
            "sales_declined": "0",
            "ecpm": 3749875.0,
            "sales_open": "0",
            "date": "2020-10-17",
            "cr": 2.19,
            "ecpc": 6.57,
            "clicks": 1143,
        },
        {
            "sales_approved": "0",
            "leads_approved": "0",
            "currency": "UAH",
            "ctr": 0.0,
            "views": 0,
            "payment_sum_declined": 0.0,
            "payment_sum_open": 2459.72,
            "payment_sum_approved": 0.0,
            "leads_declined": "0",
            "leads_open": "8",
            "sales_declined": "0",
            "ecpm": 0.0,
            "sales_open": "1",
            "date": "2020-10-16",
            "cr": 5.36,
            "ecpc": 14.65,
            "clicks": 168,
        },
        {
            "sales_approved": "0",
            "leads_approved": "0",
            "currency": "UAH",
            "ctr": 23900.0,
            "views": 1,
            "payment_sum_declined": 0.0,
            "payment_sum_open": 3254.28,
            "payment_sum_approved": 0.0,
            "leads_declined": "0",
            "leads_open": "10",
            "sales_declined": "0",
            "ecpm": 3254280.0,
            "sales_open": "6",
            "date": "2020-10-15",
            "cr": 6.69,
            "ecpc": 13.62,
            "clicks": 239,
        },
        {
            "sales_approved": "0",
            "leads_approved": "0",
            "currency": "UAH",
            "ctr": 830.77,
            "views": 26,
            "payment_sum_declined": 0.0,
            "payment_sum_open": 5828.58,
            "payment_sum_approved": 0.0,
            "leads_declined": "0",
            "leads_open": "19",
            "sales_declined": "0",
            "ecpm": 224176.16,
            "sales_open": "4",
            "date": "2020-10-14",
            "cr": 10.65,
            "ecpc": 26.99,
            "clicks": 216,
        },
        {
            "sales_approved": "0",
            "leads_approved": "0",
            "currency": "UAH",
            "ctr": 0.0,
            "views": 0,
            "payment_sum_declined": 0.0,
            "payment_sum_open": 4831.7,
            "payment_sum_approved": 0.0,
            "leads_declined": "0",
            "leads_open": "15",
            "sales_declined": "0",
            "ecpm": 0.0,
            "sales_open": "3",
            "date": "2020-10-13",
            "cr": 5.96,
            "ecpc": 16.0,
            "clicks": 302,
        },
        {
            "sales_approved": "0",
            "leads_approved": "0",
            "currency": "UAH",
            "ctr": 524.14,
            "views": 58,
            "payment_sum_declined": 0.0,
            "payment_sum_open": 6489.31,
            "payment_sum_approved": 0.0,
            "leads_declined": "0",
            "leads_open": "21",
            "sales_declined": "0",
            "ecpm": 111884.66,
            "sales_open": "3",
            "date": "2020-10-12",
            "cr": 7.89,
            "ecpc": 21.35,
            "clicks": 304,
        },
        {
            "sales_approved": "0",
            "leads_approved": "0",
            "currency": "UAH",
            "ctr": 1700.0,
            "views": 3,
            "payment_sum_declined": 0.0,
            "payment_sum_open": 299.99,
            "payment_sum_approved": 0.0,
            "leads_declined": "0",
            "leads_open": "1",
            "sales_declined": "0",
            "ecpm": 99996.67,
            "sales_open": "0",
            "date": "2020-10-11",
            "cr": 1.96,
            "ecpc": 5.89,
            "clicks": 51,
        },
        {
            "sales_approved": "0",
            "leads_approved": "0",
            "currency": "UAH",
            "ctr": 295.65,
            "views": 23,
            "payment_sum_declined": 0.0,
            "payment_sum_open": 1502.48,
            "payment_sum_approved": 0.0,
            "leads_declined": "0",
            "leads_open": "5",
            "sales_declined": "0",
            "ecpm": 65325.22,
            "sales_open": "1",
            "date": "2020-10-10",
            "cr": 8.82,
            "ecpc": 22.1,
            "clicks": 68,
        },
        {
            "sales_approved": "0",
            "leads_approved": "0",
            "currency": "UAH",
            "ctr": 0.0,
            "views": 0,
            "payment_sum_declined": 0.0,
            "payment_sum_open": 299.99,
            "payment_sum_approved": 0.0,
            "leads_declined": "0",
            "leads_open": "1",
            "sales_declined": "0",
            "ecpm": 0.0,
            "sales_open": "0",
            "date": "2020-10-09",
            "cr": 4.0,
            "ecpc": 12.0,
            "clicks": 25,
        },
        {
            "sales_approved": "0",
            "leads_approved": "0",
            "currency": "UAH",
            "ctr": 0.0,
            "views": 0,
            "payment_sum_declined": 0.0,
            "payment_sum_open": 0.0,
            "payment_sum_approved": 0.0,
            "leads_declined": "0",
            "leads_open": "0",
            "sales_declined": "0",
            "ecpm": 0.0,
            "sales_open": "0",
            "date": "2020-10-08",
            "cr": 0.0,
            "ecpc": 0.0,
            "clicks": 3,
        },
        {
            "sales_approved": "0",
            "leads_approved": "0",
            "currency": "UAH",
            "ctr": 0.0,
            "views": 0,
            "payment_sum_declined": 0.0,
            "payment_sum_open": 0.0,
            "payment_sum_approved": 0.0,
            "leads_declined": "0",
            "leads_open": "0",
            "sales_declined": "0",
            "ecpm": 0.0,
            "sales_open": "0",
            "date": "2020-10-05",
            "cr": 0.0,
            "ecpc": 0.0,
            "clicks": 6,
        },
    ];
}
